In [1]:
import pandas as pd

In [2]:
path_sam = "/home/owkin/project/experiments/sam/sam_gt_tiles_05_04.csv"

df_metrics_sam = pd.read_csv(path_sam)

df_metrics_sam = df_metrics_sam.rename(columns={"Unnamed: 0": "tile_id"})

In [3]:
df_metrics_sam

,tile_id,ensemble_dice,IoUByInstance_all_classes,IoUByInstance_class_2,dq,tp,fp,pq,sq,fn
0,3521541,0.502790,0.718588,0.718588,0.776978,108.0,31.0,0.615768,0.792517,31.0
1,6619042,0.517792,0.648351,0.648351,0.613065,122.0,77.0,0.474640,0.774208,77.0
2,65331257,0.560320,0.716130,0.716130,0.829787,39.0,8.0,0.661970,0.797758,8.0
3,67912873,0.593469,0.723965,0.723965,0.776398,125.0,36.0,0.618902,0.797146,36.0
4,84715806,0.612138,0.634156,0.634156,0.677778,61.0,29.0,0.494185,0.729126,29.0
5,96202074,0.104325,0.653210,0.653210,0.617978,110.0,68.0,0.469528,0.759782,68.0

In [5]:
df_metrics_sam[["ensemble_dice", "IoUByInstance_all_classes", "fn", "dq", "sq", "tp", "pq", "fp"]].mean()

ensemble_dice                 0.481806
IoUByInstance_all_classes     0.682400
fn                           41.500000
dq                            0.715331
sq                            0.775089
tp                           94.166667
pq                            0.555832
fp                           41.500000
dtype: float64

In [8]:
path_nuclick = "/home/owkin/project/experiments/nuclick/test_on_ground_truth_tiles/metrics_per_tile.csv"

df_metrics_nuclick = pd.read_csv(path_nuclick)

df_metrics_nuclick = df_metrics_nuclick.rename(columns={"Unnamed: 0": "tile_id"})

In [9]:
df_metrics_nuclick

,tile_id,location_id,coords,slide_name,abstra_slide_path,cytomine_username,timestamp_pushed,timestamp_row_creation,timestamp_pulled,ensemble_dice,IoUByInstance_all_classes,IoUByInstance_class_2,fn,dq,sq,tp,pq,fp,n_tiles
0,3521541,61620116,"((8512, 27776), 0, (448, 448))",TCGA-G8-6907-01Z-00-DX1.71ada905-9b5b-4757-8df...,/home/owkin/data/TCGA_DLBC/histology/raw/paraf...,kvonloga,2024-02-29 17:17:43.016614,2024-02-29 17:11:15.361112,2024-03-06 08:36:40.857167,0.774992,0.791329,0.791329,18.0,0.870504,0.810539,121.0,0.705577,18.0,1.0
1,6619042,30647803,"((23744, 33152), 0, (448, 448))",TCGA-FA-A6HO-01Z-00-DX1.9E6256E7-5C4A-4D57-981...,/home/owkin/data/TCGA_DLBC/histology/raw/paraf...,kvonloga,2024-02-29 17:18:34.208966,2024-02-29 17:11:15.361112,2024-03-06 08:36:45.387595,0.614097,0.761609,0.761609,41.0,0.793970,0.773058,158.0,0.613785,41.0,1.0
2,65331257,13867410,"((7616, 47040), 0, (448, 448))",TCGA-UT-A88E-01Z-00-DX3.B727FAE0-4562-4976-A89...,/home/owkin/data/TCGA_MESO/histology/raw/paraf...,kvonloga,2024-02-29 17:19:21.788104,2024-02-29 17:11:15.361112,2024-03-06 08:36:46.458847,0.792018,0.787405,0.787405,3.0,0.936170,0.799791,44.0,0.748740,3.0,1.0
3,67912873,52453855,"((37632, 66304), 0, (448, 448))",TCGA-LK-A4NZ-01Z-00-DX1.8A842571-2333-4957-A88...,/home/owkin/data/TCGA_MESO/histology/raw/paraf...,kvonloga,2024-02-29 17:20:10.148827,2024-02-29 17:11:15.361112,2024-03-06 08:36:50.062458,0.741173,0.767319,0.767319,18.0,0.888199,0.774142,143.0,0.687592,18.0,1.0
4,84715806,50554353,"((9856, 18816), 0, (448, 448))",TCGA-C4-A0F6-01Z-00-DX1.05FAB26A-4BE9-42B4-95F...,/home/owkin/data/TCGA_BLCA/histology/raw/paraf...,kvonloga,2024-02-29 17:20:22.680434,2024-02-29 17:11:15.361112,2024-03-06 08:36:52.140282,0.692484,0.707149,0.707149,16.0,0.822222,0.739935,74.0,0.608391,16.0,1.0
5,96202074,95145984,"((90496, 52864), 0, (448, 448))",TCGA-CU-A3QU-01Z-00-DX1.661F12B3-2865-468B-828...,/home/owkin/data/TCGA_BLCA/histology/raw/paraf...,kvonloga,2024-02-29 17:22:01.046305,2024-02-29 17:11:15.361112,2024-03-06 08:36:56.247600,0.747585,0.713017,0.713017,30.0,0.831461,0.752802,148.0,0.625926,30.0,1.0

In [14]:
df_metrics_nuclick[["ensemble_dice", "IoUByInstance_all_classes", "fn", "dq", "sq", "tp", "pq", "fp"]].mean()

ensemble_dice                  0.727058
IoUByInstance_all_classes      0.754638
fn                            21.000000
dq                             0.857088
sq                             0.775044
tp                           114.666667
pq                             0.665002
fp                            21.000000
dtype: float64